env: staging
staging:
  redis:
    url: "redis://travis:211dae3157ee02fc509af84b046803d9@filefish.redistogo.com:9086"
  reporter:
    http:
      url: "http://svenfuchs:lNBFeblTc3hJok5w6s4W@travis-staging.heroku.com/builds"
queue: erlang
shell:
<<<<<<< HEAD
  buffer: 1.0
=======
  buffer: 0.25
vms:
  count: 5
  base: lucid32_old
  memory: 1536
  cookbooks: 'vendor/cookbooks/vagrant_base'
  log_level: 'info'
  json:
    travis_build_environment:
      use_tmpfs: false
    rvm:
      rubies:
        - 1.8.6
        - 1.8.7
        - 1.8.7-p249
        - 1.9.2
        - 1.9.1-p378
        - jruby
        - rbx
        - rbx-2.0.0pre
        - ree
        - ruby-head
      gems:
        - bundler
        - rake
        - chef
      aliases:
        rbx-2.0.0pre: rbx-2.0
        1.9.1-p378:   1.9.1
    mysql:
      server_root_password: ""
    postgresql:
      max_connections: 256
  recipes:
    - travis_build_environment
    - apt
    - build-essential
    - scons
    - networking_basic
    - openssl
    - sysctl
    - libyaml # libyaml MUST be installed before rubies. MK.
    - emacs::nox
    - vim
    - timetrap
    - git
    - java
    - libqt4
    - libv8
    - nodejs
    - rvm
    - rvm::multi
    - sqlite
    - postgresql::client
    - postgresql::server
    - mysql::client
    - mysql::server
    - redis
    - riak
    - mongodb
    - memcached
    - rabbitmq
    - imagemagick
    - sphinx
    - xvfb
>>>>>>> 399829b238545327a7e2ce7707fae7fd96573fd7
