env: staging
staging:
  redis:
    url: "redis://travis:211dae3157ee02fc509af84b046803d9@filefish.redistogo.com:9086"
  reporter:
    http:
      url: "http://svenfuchs:lNBFeblTc3hJok5w6s4W@travis-staging.heroku.com/builds"
queue: erlang
shell:
  buffer: 1.0
